Feat/memory
sayajin-labs/kakarot-ssj pull request #34
Opened 2023-05-09 09:00 UTC by enitrat

Cairo 1 implementation of Kakarot's memory
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2023-05-09 11:23 UTC, enitrat commented
A few questions: 
- Does the `load_word` function needTO more than 16 bytes? If yes, I will change the return type to `u256` - otherwise, let's keep it as `u128`
- I see [here ](https://github.com/sayajin-labs/kakarot/blob/main/src/utils/utils.cairo#L383) a special `div_rem` function that handles the `div = 2**128` case. What is it for? I couldn't understand it.

2023-05-09 14:09 UTC, ClementWalter requested changes
I realized at the middle of the review that this is really a close copy/paste (even the comments) to the cairo 0.x version, so some question may be postponed.

Regarding test files naming, it seems like we miss a consensus in between test prefix (e.g. `test_memory.cairo`) and suffix (e.g. `kakarot_test.cairo`). I'm wondering if this (prefix or suffix) should be kept as test detection doesn't use this anymore right ? (unlike pytest for instance that needs this)

2023-05-09 14:09 UTC, ClementWalter commented on src/utils/helpers.cairo
> +    let FELT252_PRIME: u256 = 0x800000000000011000000000000000000000000000000000000000000000001;
isn't already a constant available somewhere for this? could we otherwise move this somewhere apart?

2023-05-09 14:19 UTC, enitrat commented on Makefile
> +	sh scripts/generate_cairo_project.sh && cairo-test $(TEST_ENTRYPOINT)
this script reads the `Scarb.toml` file, extracts the dependencies, and adds them as crate roots in the `cairo_project.toml` file. Given that this is only used to run `cairo-test`, I thought that doing it when running `make test` would make sense, in case new dependencies were added, and so that this process is abstracted.

We can separate it in two steps and have a `make cairo-project` and then `make test` but the benefit is low

2023-05-09 14:21 UTC, enitrat commented on src/memory.cairo
> +    fn print_mem(ref self: Memory, mut begin: usize, end: usize) {
`mut` is just a modifier that allows mutating the variable in the function. It can't be used in the signature in the trait.

2023-05-09 14:22 UTC, enitrat commented on src/memory.cairo
> +trait MemoryPrintTrait<T> {
Not really, it can directly be modified to

```
trait MemoryPrintTrait{
    fn print_mem(ref self: Memory, begin: usize, end: usize);
}
```

In the future, the trait can even be abstracted, given that `impl` without traits are [planned](https://github.com/starkware-libs/cairo/issues/3019)

2023-05-09 14:24 UTC, enitrat commented on src/memory.cairo
> +    fn print_mem(ref self: T, begin: usize, end: usize);
There's an existing trait called `PrintTrait` in the corelibrary that defines a method `print` defining how to print a type `T`.
However, this method takes ownership of `T` - for most types, it doesn't matter as they can be implicitly copied.

In the body of this function, we call `self.items.get(begin.into()).print();`, therefore there's a name clash if the function is called `print` aswell

2023-05-09 14:32 UTC, enitrat commented on src/memory.cairo
> +        ref self: Memory, chunk_index: usize, chunk_index_f: usize, elements: Span<u8>
`chunk_index` is the beginning chunk to start storing at, while `chunk_index_f` is the ending chunk.

The memory is actually not composed by 32bytes words, but rather by two consecutive 16bytes words expressed as u128, which we can reassemble to u256.

Imagine that we have a byte array of 32 bytes (2 chunks of 16 bytes each) to be stored in the memory structure. It looks something like this:
```
Byte array (elements):
[ B1, B2, B3, B4, B5, B6, ...etc, B32 ]
```

We can store them in memory like this:

```
chunk_index   |   value
-----------------------------------------
      0       |   (B1*256^15 + B2*256^14 + B3*256^13 + ... + B16*256^0)
      1       |   (B17*256^15 + B18*256^14 + B19*256^13 + ... + B32*256^0)
```

Given this array of 32 bytes, this function will store them in two consecutive 16 bytes chunks of memory. 
In that case, we will call it with `chunk_index = 0` and `chunk_index_f = 2`. These 32bytes will be combined in two 128bits values, and stored in chunk 0 and chunk 1.

2023-05-09 14:37 UTC, enitrat commented on src/memory.cairo
> +        self.bytes_len = new_bytes_len;
We could but then we still need to determine what's the new minimum bytes length required, right?

In this situation
- `offset = 10`
- `self.bytes_len = 32`

then, we can determine that `offset+32 > self.bytes_len` and that we need to update `self.bytes_len`
But we still have to figure out which multiple of 32 to use, so we will compute `(offset+32 +31)/32` anyway, not saving any steps. 

Is that what you were thinking about?

2023-05-09 14:38 UTC, enitrat commented on src/memory.cairo
> +        let mask_c: u256 = utils::pow(2, 128).into() / mask;
it stands for complementary. `mask_c` is the complementary of `mask`

2023-05-09 14:40 UTC, enitrat commented on Scarb.toml
> -quaireaux = { git = "https://github.com/keep-starknet-strange/quaireaux.git" }
Quaireaux is not dead but its structure changed, and we're not using it for anything ATM.

2023-05-09 14:41 UTC, enitrat commented on src/utils.cairo
> +    if exp == 0 {
not yet

2023-05-09 14:42 UTC, enitrat commented on src/utils/helpers.cairo
> +use array::ArrayTrait;
This structure is inherited from the Cairo0 implementation and can (should) be re-worked. We can discuss this

2023-05-09 14:44 UTC, enitrat commented on src/utils/helpers.cairo
> +        dst.append(low_part.try_into().unwrap());
We could, however, I would not name it `into` as it refers to a safe operation from the core library. We should find another name that _explicitly_ indicates that it truncates the value

2023-05-09 14:48 UTC, enitrat commented
> I'm wondering if this (prefix or suffix) should be kept as test detection doesn't use this anymore right ? (unlike pytest for instance that needs this)

I am in favor of having test files named as `test_filename.cairo`, even though it's not mandatory.
The current test runner is the native `cairo-test`, which only relies on `#[test]` attributes above functions to run tests. But it helps keep the codebase clean, and it's easier to know if compilation issues come from testfiles or source files.

2023-05-09 15:06 UTC, enitrat commented on src/memory.cairo
> +        );
if `mask = 1`, therefore `mask_c = (2**128 / 1) = 2**128`
The max value that can fit in a u128 is `2**128 - 1`

Therefore, `mask_c` is `u256` and we need to do computations with `u256`

2023-05-09 15:11 UTC, enitrat commented on src/memory.cairo
> +        let mask_c: u256 = utils::pow(2, 128).into() / mask;
I didn't understand the question

2023-05-09 15:21 UTC, ClementWalter commented on Makefile
> +	sh scripts/generate_cairo_project.sh && cairo-test $(TEST_ENTRYPOINT)
yes plz, a separate entry and some comments about the why we need this, and possibly a link to `scarb eject` you mentioned

2023-05-09 15:31 UTC, ClementWalter commented on src/memory.cairo
> +    fn print_mem(ref self: T, begin: usize, end: usize);
so maybe `print_segment` ? 😇

2023-05-09 15:49 UTC, ClementWalter commented on src/memory.cairo
> +        ref self: Memory, chunk_index: usize, chunk_index_f: usize, elements: Span<u8>
ok sorry I was thinking about the trailing `_f` as we generally don't accept such murky naming in the codebase, but blaming from the cairo 0.x version it came from @ spapinistarkware memory refacto..! I don't know why he didn't iterate through  `element_len`, which have looked more natural to me

```
fn store_aligned_words(ref self: Memory, chunk_index: usize, element_len: usize, elements: Span<u8>
```

but now, I guess that we should remove this arg and use `elements.len()`

2023-05-09 15:52 UTC, ClementWalter commented on src/memory.cairo
> +        self.bytes_len = new_bytes_len;
sorry I missed the fact that we can write at any location and not only at the end of the already written memory, you can forget this comment

2023-05-09 16:00 UTC, ClementWalter commented on src/memory.cairo
> +        let mask_c: u256 = utils::pow(2, 128).into() / mask;
I made a type indo, just fixed it. I was thinking about (in terms of math):

```mask = 256 ** (16 - offset)```

then you compute

```mask_c = 2 ** 128 / mask = 256 ** 16 / mask```

ie using `mask` variable. Does this take the same number of step, less or more than computing directly without using `mask` (possibly with an hard coded pow table like in `helpers::pow_rev`):

```
mask_c = 256 ** offset
```

2023-05-09 18:02 UTC, enitrat commented on src/memory.cairo
> +        ref self: Memory, chunk_index: usize, chunk_index_f: usize, elements: Span<u8>
That's what I've already done ;)

2023-05-09 18:09 UTC, enitrat commented on src/memory.cairo
> +impl U256TryIntoU128 of TryInto<u256, u128> {
yes, ideally it's in the core library. I will move this to `utils::helpers`

2023-05-10 09:12 UTC, ClementWalter requested changes

2023-05-10 09:12 UTC, ClementWalter commented on src/memory.cairo
> +        ref self: Memory, chunk_index: usize, chunk_index_f: usize, elements: Span<u8>
<img width="498" alt="image" src="https://github.com/sayajin-labs/kakarot-ssj/assets/18620296/1f10c2dc-c60d-4f20-a80a-24b40ebedbef">
the arg is here afaik

2023-05-10 09:12 UTC, ClementWalter commented on src/memory.cairo
> +        let mask_c: u256 = utils::pow(2, 128).into() / mask;
any input on this?

2023-05-10 09:12 UTC, ClementWalter commented on src/utils/helpers.cairo
> +    if i == 0 {
could we use `match` here instead?

2023-05-10 09:12 UTC, ClementWalter commented on src/utils/helpers.cairo
> +        dst.append(low_part.try_into().unwrap());
I'm not sure about the _safe_ but in the EVM world, it's not _unsafe_ to do this. anyway, we'll think about this when refactoring the types and utils

2023-05-10 09:12 UTC, ClementWalter commented on tests/kakarot_test.cairo
is it `test_kakarot.cairo` or `kakarot_test.cairo` or `kakarot.cairo` in `tests` is enough (see my previous comment regarding this topic)

2023-05-10 09:12 UTC, ClementWalter commented on tests/lib.cairo
> +mod test_memory;
`test_memory` or `memory_test` or `memory` ?

2023-05-10 09:12 UTC, ClementWalter commented on tests/utils.cairo
> +mod test_helpers;
`test_helpers` or `helpers_test` or `helpers` ?

2023-05-10 09:26 UTC, enitrat commented on tests/kakarot_test.cairo
I will change all test files to follow the `test_filename.cairo` pattern

2023-05-10 10:12 UTC, enitrat commented on src/memory.cairo
> +        ref self: Memory, chunk_index: usize, chunk_index_f: usize, elements: Span<u8>
ah sorry I misunderstood. Will look into it

2023-05-10 10:29 UTC, enitrat commented on src/memory.cairo
> +        ref self: Memory, chunk_index: usize, chunk_index_f: usize, elements: Span<u8>
The answer is that you actually don't want to use `elements.len()` here. This method is used to store consecutive words in memory between `chunk_index` and `chunk_index_f`, but not store all bytes in the `elements` array.

Imagine if `elements.len()` is not a multiple of `16`. That would make our function call fail, as we would be trying to access an Out Of Bounds index. `chunk_index_f` is guaranteed to be a multiple of 16, therefore, `store_aligned_words` will never fail.

Any extra bytes to store will be packed in the last word.

2023-05-10 10:37 UTC, enitrat commented on src/memory.cairo
> +        let mask_c: u256 = utils::pow(2, 128).into() / mask;
I think `256 ** 16 / mask` will take less computation steps given that `pow` is a recursive function with as many operations as the exponent number. I  will use this one instead.

Just ran a small benchmark on the `test__load__should_load_an_element_from_the_memory` test.
With `256**16` it uses 498k gas, with `2**128` it uses 545k gas. good catch!

2023-05-10 10:39 UTC, enitrat commented on src/memory.cairo
> +    fn try_into(self: u256) -> Option<u128> {
This is initially not supposed to replicate the EVM's behavior, this is just an implementation of the core library `TryInto` trait.

2023-05-10 11:06 UTC, ClementWalter commented on src/memory.cairo
> +    fn try_into(self: u256) -> Option<u128> {
For the context, working with evm types in the cairo 0.x has been a mess with a lot of created wordings not following tightly the EVM one (mixing of `bytes_array`, `bytes`, `word` with different actual bytes len, etc.). As Kakarot is not a starknet lib but an EVM implementation, for the sake of clarity and simplicity, weneed to adopt a clear [ubiquitous language](https://martinfowler.com/bliki/UbiquitousLanguage.html).

So in this new repo, we'll probably have a module somewhere defining clearly all the solidity [value types](https://docs.soliditylang.org/en/v0.8.17/types.html) and their corresponding casting rules.

For the sake of completeness, returning `None` when the u256 doesn't fit into the u128 is also not obvious but a design choice, see for example the [rust TryFrom doc](https://doc.rust-lang.org/std/convert/trait.TryFrom.html) about this exact topic.

2023-05-10 11:38 UTC, ClementWalter requested changes

2023-05-10 11:38 UTC, ClementWalter commented on src/utils/helpers.cairo
> +/// The packed u128
why did you change from felt to u128 only?

2023-05-10 11:46 UTC, enitrat commented on src/utils/helpers.cairo
> +/// The packed u128
This is the question I asked above.
> Does the load_word function need to load more than 16 bytes? If yes, I will change the return type to u256 - otherwise, let's keep it as u128

2023-05-10 11:47 UTC, enitrat commented on src/utils/helpers.cairo
> +/// The packed u128
As for why not using a felt252, we should avoid using felts as much as possible as per good practices.

2023-05-10 11:55 UTC, ClementWalter commented on src/utils/helpers.cairo
> +/// The packed u128
it's u256 then plz

2023-05-10 15:08 UTC, ClementWalter submitted a review, later dismissed

2023-05-10 15:26 UTC, ClementWalter approved these changes

2023-05-11 08:04 UTC, ClementWalter approved these changes

2023-05-11 09:41 UTC, merged